# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from tangying_robot_proto.controlplane.v1 import controlplane_pb2 as controlplane_dot_v1_dot_controlplane__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in controlplane/v1/controlplane_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlPlaneStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAgent = channel.unary_unary(
                '/tangying.controlplane.v1.ControlPlane/RegisterAgent',
                request_serializer=controlplane_dot_v1_dot_controlplane__pb2.RegisterAgentRequest.SerializeToString,
                response_deserializer=controlplane_dot_v1_dot_controlplane__pb2.RegisterAgentResponse.FromString,
                _registered_method=True)
        self.ClaimTask = channel.unary_unary(
                '/tangying.controlplane.v1.ControlPlane/ClaimTask',
                request_serializer=controlplane_dot_v1_dot_controlplane__pb2.ClaimTaskRequest.SerializeToString,
                response_deserializer=controlplane_dot_v1_dot_controlplane__pb2.ClaimTaskResponse.FromString,
                _registered_method=True)
        self.RenewLease = channel.unary_unary(
                '/tangying.controlplane.v1.ControlPlane/RenewLease',
                request_serializer=controlplane_dot_v1_dot_controlplane__pb2.RenewLeaseRequest.SerializeToString,
                response_deserializer=controlplane_dot_v1_dot_controlplane__pb2.RenewLeaseResponse.FromString,
                _registered_method=True)
        self.AppendTaskEvent = channel.unary_unary(
                '/tangying.controlplane.v1.ControlPlane/AppendTaskEvent',
                request_serializer=controlplane_dot_v1_dot_controlplane__pb2.AppendTaskEventRequest.SerializeToString,
                response_deserializer=controlplane_dot_v1_dot_controlplane__pb2.AppendTaskEventResponse.FromString,
                _registered_method=True)


class ControlPlaneServicer:
    """Missing associated documentation comment in .proto file."""

    def RegisterAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendTaskEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlPlaneServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=controlplane_dot_v1_dot_controlplane__pb2.RegisterAgentRequest.FromString,
                    response_serializer=controlplane_dot_v1_dot_controlplane__pb2.RegisterAgentResponse.SerializeToString,
            ),
            'ClaimTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimTask,
                    request_deserializer=controlplane_dot_v1_dot_controlplane__pb2.ClaimTaskRequest.FromString,
                    response_serializer=controlplane_dot_v1_dot_controlplane__pb2.ClaimTaskResponse.SerializeToString,
            ),
            'RenewLease': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewLease,
                    request_deserializer=controlplane_dot_v1_dot_controlplane__pb2.RenewLeaseRequest.FromString,
                    response_serializer=controlplane_dot_v1_dot_controlplane__pb2.RenewLeaseResponse.SerializeToString,
            ),
            'AppendTaskEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendTaskEvent,
                    request_deserializer=controlplane_dot_v1_dot_controlplane__pb2.AppendTaskEventRequest.FromString,
                    response_serializer=controlplane_dot_v1_dot_controlplane__pb2.AppendTaskEventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tangying.controlplane.v1.ControlPlane', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tangying.controlplane.v1.ControlPlane', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlPlane:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tangying.controlplane.v1.ControlPlane/RegisterAgent',
            controlplane_dot_v1_dot_controlplane__pb2.RegisterAgentRequest.SerializeToString,
            controlplane_dot_v1_dot_controlplane__pb2.RegisterAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tangying.controlplane.v1.ControlPlane/ClaimTask',
            controlplane_dot_v1_dot_controlplane__pb2.ClaimTaskRequest.SerializeToString,
            controlplane_dot_v1_dot_controlplane__pb2.ClaimTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenewLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tangying.controlplane.v1.ControlPlane/RenewLease',
            controlplane_dot_v1_dot_controlplane__pb2.RenewLeaseRequest.SerializeToString,
            controlplane_dot_v1_dot_controlplane__pb2.RenewLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendTaskEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tangying.controlplane.v1.ControlPlane/AppendTaskEvent',
            controlplane_dot_v1_dot_controlplane__pb2.AppendTaskEventRequest.SerializeToString,
            controlplane_dot_v1_dot_controlplane__pb2.AppendTaskEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
