# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from tangying_robot_proto.robot.v1 import robot_pb2 as robot_dot_v1_dot_robot__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in robot/v1/robot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotRuntimeStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRuntimeInfo = channel.unary_unary(
                '/tangying.robot.v1.RobotRuntime/GetRuntimeInfo',
                request_serializer=robot_dot_v1_dot_robot__pb2.GetRuntimeInfoRequest.SerializeToString,
                response_deserializer=robot_dot_v1_dot_robot__pb2.RuntimeInfo.FromString,
                _registered_method=True)
        self.Observe = channel.unary_stream(
                '/tangying.robot.v1.RobotRuntime/Observe',
                request_serializer=robot_dot_v1_dot_robot__pb2.ObserveRequest.SerializeToString,
                response_deserializer=robot_dot_v1_dot_robot__pb2.Observation.FromString,
                _registered_method=True)
        self.ExecuteSkill = channel.unary_stream(
                '/tangying.robot.v1.RobotRuntime/ExecuteSkill',
                request_serializer=robot_dot_v1_dot_robot__pb2.SkillCommand.SerializeToString,
                response_deserializer=robot_dot_v1_dot_robot__pb2.SkillEvent.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/tangying.robot.v1.RobotRuntime/Cancel',
                request_serializer=robot_dot_v1_dot_robot__pb2.CancelRequest.SerializeToString,
                response_deserializer=robot_dot_v1_dot_robot__pb2.CancelResult.FromString,
                _registered_method=True)
        self.EmergencyStop = channel.unary_unary(
                '/tangying.robot.v1.RobotRuntime/EmergencyStop',
                request_serializer=robot_dot_v1_dot_robot__pb2.EStopRequest.SerializeToString,
                response_deserializer=robot_dot_v1_dot_robot__pb2.EStopResult.FromString,
                _registered_method=True)


class RobotRuntimeServicer:
    """Missing associated documentation comment in .proto file."""

    def GetRuntimeInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Observe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteSkill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmergencyStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRuntimeInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuntimeInfo,
                    request_deserializer=robot_dot_v1_dot_robot__pb2.GetRuntimeInfoRequest.FromString,
                    response_serializer=robot_dot_v1_dot_robot__pb2.RuntimeInfo.SerializeToString,
            ),
            'Observe': grpc.unary_stream_rpc_method_handler(
                    servicer.Observe,
                    request_deserializer=robot_dot_v1_dot_robot__pb2.ObserveRequest.FromString,
                    response_serializer=robot_dot_v1_dot_robot__pb2.Observation.SerializeToString,
            ),
            'ExecuteSkill': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteSkill,
                    request_deserializer=robot_dot_v1_dot_robot__pb2.SkillCommand.FromString,
                    response_serializer=robot_dot_v1_dot_robot__pb2.SkillEvent.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=robot_dot_v1_dot_robot__pb2.CancelRequest.FromString,
                    response_serializer=robot_dot_v1_dot_robot__pb2.CancelResult.SerializeToString,
            ),
            'EmergencyStop': grpc.unary_unary_rpc_method_handler(
                    servicer.EmergencyStop,
                    request_deserializer=robot_dot_v1_dot_robot__pb2.EStopRequest.FromString,
                    response_serializer=robot_dot_v1_dot_robot__pb2.EStopResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tangying.robot.v1.RobotRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tangying.robot.v1.RobotRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotRuntime:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRuntimeInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tangying.robot.v1.RobotRuntime/GetRuntimeInfo',
            robot_dot_v1_dot_robot__pb2.GetRuntimeInfoRequest.SerializeToString,
            robot_dot_v1_dot_robot__pb2.RuntimeInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Observe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tangying.robot.v1.RobotRuntime/Observe',
            robot_dot_v1_dot_robot__pb2.ObserveRequest.SerializeToString,
            robot_dot_v1_dot_robot__pb2.Observation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteSkill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tangying.robot.v1.RobotRuntime/ExecuteSkill',
            robot_dot_v1_dot_robot__pb2.SkillCommand.SerializeToString,
            robot_dot_v1_dot_robot__pb2.SkillEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tangying.robot.v1.RobotRuntime/Cancel',
            robot_dot_v1_dot_robot__pb2.CancelRequest.SerializeToString,
            robot_dot_v1_dot_robot__pb2.CancelResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmergencyStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tangying.robot.v1.RobotRuntime/EmergencyStop',
            robot_dot_v1_dot_robot__pb2.EStopRequest.SerializeToString,
            robot_dot_v1_dot_robot__pb2.EStopResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
