#!/usr/bin/env bash
# Generate the Fleet mTLS certificate set:
#   - one CA (private key stays on the control plane host)
#   - one server certificate for the fleet gateway
#   - one client certificate per robot (CN = robot id)
#
# Output goes to deploy/cloud/certs/. Certificates are deployment secrets;
# the directory is gitignored and regenerated by scripts/fleet-up.sh.
set -euo pipefail

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)"
CERT_DIR="${FLEET_CERT_DIR:-$ROOT_DIR/deploy/cloud/certs}"
ROBOTS="${FLEET_ROBOTS:-robot-1,robot-2}"
DAYS_CA="${FLEET_CA_DAYS:-3650}"
DAYS_CERT="${FLEET_CERT_DAYS:-825}"

mkdir -p "$CERT_DIR"

if [[ ! -f "$CERT_DIR/fleet-ca.crt" ]]; then
    echo "fleet-certs: generating CA"
    openssl req -x509 -newkey rsa:3072 -nodes -sha256 \
        -keyout "$CERT_DIR/fleet-ca.key" \
        -out "$CERT_DIR/fleet-ca.crt" \
        -days "$DAYS_CA" \
        -subj "/CN=Tangying Fleet CA" >/dev/null 2>&1
else
    echo "fleet-certs: CA already present ($CERT_DIR/fleet-ca.crt)"
fi

if [[ ! -f "$CERT_DIR/fleet-server.crt" ]]; then
    echo "fleet-certs: generating fleet gateway server certificate"
    openssl req -newkey rsa:3072 -nodes -sha256 \
        -keyout "$CERT_DIR/fleet-server.key" \
        -out "$CERT_DIR/fleet-server.csr" \
        -subj "/CN=fleet-control-plane" >/dev/null 2>&1
    cat > "$CERT_DIR/fleet-server.ext" <<'EOF'
subjectAltName = DNS:localhost, DNS:fleet-control-plane, IP:127.0.0.1, IP:0.0.0.0
extendedKeyUsage = serverAuth
EOF
    openssl x509 -req -sha256 -days "$DAYS_CERT" \
        -in "$CERT_DIR/fleet-server.csr" \
        -CA "$CERT_DIR/fleet-ca.crt" -CAkey "$CERT_DIR/fleet-ca.key" -CAcreateserial \
        -extfile "$CERT_DIR/fleet-server.ext" \
        -out "$CERT_DIR/fleet-server.crt" >/dev/null 2>&1
    rm -f "$CERT_DIR/fleet-server.csr" "$CERT_DIR/fleet-server.ext"
else
    echo "fleet-certs: server certificate already present"
fi

for robot in ${ROBOTS//,/ }; do
    if [[ -f "$CERT_DIR/$robot.crt" ]]; then
        echo "fleet-certs: $robot certificate already present"
        continue
    fi
    echo "fleet-certs: generating $robot client certificate"
    openssl req -newkey rsa:3072 -nodes -sha256 \
        -keyout "$CERT_DIR/$robot.key" \
        -out "$CERT_DIR/$robot.csr" \
        -subj "/CN=$robot" >/dev/null 2>&1
    cat > "$CERT_DIR/$robot.ext" <<EOF
extendedKeyUsage = clientAuth
subjectAltName = DNS:$robot
EOF
    openssl x509 -req -sha256 -days "$DAYS_CERT" \
        -in "$CERT_DIR/$robot.csr" \
        -CA "$CERT_DIR/fleet-ca.crt" -CAkey "$CERT_DIR/fleet-ca.key" -CAcreateserial \
        -extfile "$CERT_DIR/$robot.ext" \
        -out "$CERT_DIR/$robot.crt" >/dev/null 2>&1
    rm -f "$CERT_DIR/$robot.csr" "$CERT_DIR/$robot.ext"
done

chmod 600 "$CERT_DIR"/*.key
echo "fleet-certs: done ($CERT_DIR)"
ls -1 "$CERT_DIR"
